fixed line 5 in main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,14 +49,15 @@ jobs:
       - name: Check Test Results
         run: |
           if test -f /output/succeeded; then
-            echo "Tests passed!" && exit 0
+            echo "Tests passed!"
           else
-            echo "Tests failed!" && exit 1
+            echo "Tests failed!"
+	    exit 1
 
       # Step 9: Upload result file (succeeded or fail) as an artifact
       - name: Upload test result
         uses: actions/upload-artifact@v3
         with:
           name: test-result
-          path: /output/succeeded  # or /output/fail
+          path: /output
 
